name = "LeanPython"
version = "0.1.0"
defaultTargets = ["LeanPython"]
testDriver = "LeanPythonTest"

[[lean_lib]]
name = "LeanPython"

[[lean_lib]]
name = "LeanPythonTest"
globs = ["LeanPythonTest.+"]

[[lean_exe]]
name = "leanPython"
root = "Main"
